# Generated by Django 4.2.5 on 2023-09-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='')),
                ('text', models.TextField()),
                ('published_time', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField()),
            ],
        ),
    ]
