# Generated by Django 4.2.5 on 2023-10-10 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weddad', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userposts', to=settings.AUTH_USER_MODEL),
        ),
    ]
