# Generated by Django 4.2.5 on 2023-10-11 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weddad', '0008_remove_post_author_alter_post_author2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=80)),
                ('Transport_costs', models.IntegerField(null=True)),
                ('Food_costs', models.IntegerField(null=True)),
                ('Other_costs', models.IntegerField(null=True)),
                ('Total', models.IntegerField(null=True)),
                ('Creatur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userplans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
