# Generated by Django 4.2.5 on 2023-10-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddad', '0009_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='Total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
