# Generated by Django 4.2.5 on 2023-10-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddad', '0010_alter_plan_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='Descreption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='Target',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
