# Generated by Django 4.2.5 on 2023-10-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddad', '0011_plan_descreption_plan_target_plan_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='Target',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='plan',
            name='date',
            field=models.DateField(),
        ),
    ]
