# Generated by Django 4.2.5 on 2023-10-13 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weddad', '0012_alter_plan_target_alter_plan_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan_member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(blank=True, max_length=25, null=True)),
                ('status', models.CharField(blank=True, default='Non')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='weddad.plan')),
            ],
        ),
    ]
