# Generated by Django 4.2.5 on 2023-10-13 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weddad', '0013_plan_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan_member',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planmem', to='weddad.plan'),
        ),
    ]
