# Generated by Django 4.2.5 on 2023-10-13 17:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weddad', '0016_alter_plan_member_member'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plan_member',
            new_name='Plan_member2',
        ),
    ]
