# Generated by Django 4.2.5 on 2023-10-13 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weddad', '0018_plan_member3_delete_plan_member2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan_member3',
            name='member',
        ),
    ]
