# Generated by Django 4.2.6 on 2023-10-31 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weddad', '0021_post_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day_Planner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('morning', models.TextField(blank=True, null=True)),
                ('middle_day', models.TextField(blank=True, null=True)),
                ('night', models.TextField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='weddad.plan')),
            ],
        ),
    ]
