# Generated by Django 4.2.6 on 2023-11-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddad', '0022_day_planner'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='fin_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='Food_costs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='Other_costs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='Transport_costs',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
