# Generated by Django 4.2.6 on 2023-11-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddad', '0023_plan_fin_date_alter_plan_food_costs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='Food_costs',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='plan',
            name='Other_costs',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='plan',
            name='Total',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='plan',
            name='Transport_costs',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='plan',
            name='fin_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
