# Generated by Django 4.2.6 on 2023-11-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddad', '0026_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
